// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMOhHebURGdOXPNJwZbD0wj5g6mD0Ung',
    appId: '1:110644008939:web:043647f939b89414e8abae',
    messagingSenderId: '110644008939',
    projectId: 'fruit-hup',
    authDomain: 'fruit-hup.firebaseapp.com',
    storageBucket: 'fruit-hup.appspot.com',
    measurementId: 'G-JPFK9HBFS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcy-mORknOGvsMiJZygejNKcoWLBmkBk8',
    appId: '1:110644008939:android:45ae7d931d1d5b6ee8abae',
    messagingSenderId: '110644008939',
    projectId: 'fruit-hup',
    storageBucket: 'fruit-hup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZTY6cYjIINhO-Mv_R39aQ27FVLzEgAM',
    appId: '1:110644008939:ios:0936a51e6bc212d8e8abae',
    messagingSenderId: '110644008939',
    projectId: 'fruit-hup',
    storageBucket: 'fruit-hup.appspot.com',
    iosBundleId: 'com.example.fruitHubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZTY6cYjIINhO-Mv_R39aQ27FVLzEgAM',
    appId: '1:110644008939:ios:0936a51e6bc212d8e8abae',
    messagingSenderId: '110644008939',
    projectId: 'fruit-hup',
    storageBucket: 'fruit-hup.appspot.com',
    iosBundleId: 'com.example.fruitHubAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXMOhHebURGdOXPNJwZbD0wj5g6mD0Ung',
    appId: '1:110644008939:web:deeb479c0232751ae8abae',
    messagingSenderId: '110644008939',
    projectId: 'fruit-hup',
    authDomain: 'fruit-hup.firebaseapp.com',
    storageBucket: 'fruit-hup.appspot.com',
    measurementId: 'G-TB8GRGR0Z1',
  );
}
